# Generated by Django 5.2.12 on 2026-04-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_billing_plan_packages'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userapikey',
            new_name='users_usera_key_has_a2c5c2_idx',
            old_name='userapikey_hash_idx',
        ),
        migrations.RenameIndex(
            model_name='userapikey',
            new_name='users_usera_user_id_0dd2f2_idx',
            old_name='userapikey_user_act_idx',
        ),
    ]
