# Generated by Django 5.2.12 on 2026-03-28 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0003_formcollaborator'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'ordering': ['-updated_at']},
        ),
    ]
