# Generated by Django 5.2.12 on 2026-03-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0004_alter_form_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='thank_you_message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
