# Generated by Django 5.2.12 on 2026-03-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_app', '0005_form_thank_you_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='appearance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
